export default function DisclaimerPage() {
  return (
    <div className="max-w-3xl mx-auto py-12 px-6 prose prose-blue">
      <h1>Disclaimer</h1>
      <p className="text-gray-500">Last Updated: June 15, 2026</p>

      <p>The content generated by Jules is intended for educational and assistant purposes only. While we strive for high quality, the AI may occasionally produce inaccurate or outdated information.</p>

      <p><strong>Use at your own risk:</strong> Jules does not guarantee that the generated documentation will meet specific college or university requirements. Users must review and verify all content before submission.</p>

      <p>Jules AI is not affiliated with any educational institution.</p>
    </div>
  );
}
